
// Code generated by Script. DO NOT EDIT.
// Source: script/codegen/main.go
//
// Generated by this command:
//
//	go run script/codegen/main.go

package zendesk

import "context"

func (z *Client) GetBrandsIterator(ctx context.Context, opts *PaginationOptions) *Iterator[Brand] {
	return &Iterator[Brand]{
		CommonOptions: opts.CommonOptions,
		pageSize:      opts.PageSize,
		hasMore:       true,
		isCBP:         opts.IsCBP,
		pageAfter:     "",
		pageIndex:     1,
		ctx:           ctx,
		obpFunc:       z.GetBrandsOBP,
		cbpFunc:       z.GetBrandsCBP,
	}
}

func (z *Client) GetBrandsOBP(ctx context.Context, opts *OBPOptions) ([]Brand, Page, error) {
	var data struct {
		Brands []Brand `json:"brands"`
		Page
	}

	tmp := opts
	if tmp == nil {
		tmp = &OBPOptions{}
	}
	
	u, err := addOptions("/brands.json", tmp)
	
	if err != nil {
		return nil, Page{}, err
	}

	err = getData(z, ctx, u, &data)
	if err != nil {
		return nil, Page{}, err
	}
	return data.Brands, data.Page, nil
}

func (z *Client) GetBrandsCBP(ctx context.Context, opts *CBPOptions) ([]Brand, CursorPaginationMeta, error) {
	var data struct {
		Brands []Brand `json:"brands"`
		Meta    CursorPaginationMeta `json:"meta"`
	}

	tmp := opts
	if tmp == nil {
		tmp = &CBPOptions{}
	}
	
	u, err := addOptions("/brands.json", tmp)
	
	if err != nil {
		return nil, data.Meta, err
	}

	err = getData(z, ctx, u, &data)
	if err != nil {
		return nil, data.Meta, err
	}
	return data.Brands, data.Meta, nil
}

